-- migrate:up
CREATE USER aleks WITH PASSWORD 'aleks';

ALTER SCHEMA core OWNER TO aleks;

GRANT USAGE ON SCHEMA core TO aleks;
GRANT CREATE ON SCHEMA core TO aleks;

--- Grants privileges to existing db objects
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA core TO aleks;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA core TO aleks;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA core TO aleks;

--- Grants privileges to future db objects
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT ALL ON TABLES TO aleks;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT ALL ON SEQUENCES TO aleks;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT ALL ON FUNCTIONS TO aleks;

-- migrate:down
ALTER DEFAULT PRIVILEGES IN SCHEMA core REVOKE ALL ON TABLES FROM aleks;
ALTER DEFAULT PRIVILEGES IN SCHEMA core REVOKE ALL ON SEQUENCES FROM aleks;
ALTER DEFAULT PRIVILEGES IN SCHEMA core REVOKE ALL ON FUNCTIONS FROM aleks;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA core FROM aleks;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA core FROM aleks;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA core FROM aleks;

REVOKE USAGE ON SCHEMA core FROM aleks;
REVOKE CREATE ON SCHEMA core FROM aleks;

ALTER SCHEMA core OWNER TO admin;

DROP USER aleks;
